language: python

sudo: false

cache:
  - pip

python:
 - "2.7"
 - "3.6"
 - "3.7-dev"

env:
  global:
    - AWS_ACCESS_KEY_ID="MOCK_ACCESS_KEY_ID"
    - AWS_SECRET_ACCESS_KEY="MOCK_SECRET_ACCESS_KEY"
  matrix:
    - DJANGO_VERSION=1.11.*
    - DJANGO_VERSION=2.0.*
    - DJANGO_VERSION=2.1.*

matrix:
  exclude:
  - python: "2.7"
    env: DJANGO_VERSION=2.0.*
  - python: "2.7"
    env: DJANGO_VERSION=2.1.*

install:
 # Testing dependencies
 - pip install flake8 coverage python-coveralls moto
 # Required library dependencies
 - pip install boto3 six fs
 # Optional library dependencies
 - pip install celery
 # The version of Django being tested against
 - pip install -q Django==$DJANGO_VERSION

script:
 - flake8 bakery
 - coverage run setup.py test
 - coverage report -m

after_success:
 - coveralls
