language: python

sudo: false

python:
 - "2.7"
 - "3.5"

env:
 - DJANGO_VERSION=1.8.14
 - DJANGO_VERSION=1.9.9
 - DJANGO_VERISON="1.10"

install:
 # Testing dependencies
 - pip install pyflakes pep8 coverage python-coveralls moto
 # Required library dependencies
 - pip install boto six
 # Optional library dependencies
 - pip install celery django-celery django-kombu
 # The version of Django being tested against
 - pip install -q Django==$DJANGO_VERSION

script:
 - pep8 bakery
 - pyflakes bakery
 - coverage run setup.py test

after_success:
 - coveralls
