language: python

sudo: false

cache:
  - pip

python:
 - "2.7"
 - "3.5"

env:
 - DJANGO_VERSION=1.7.11
 - DJANGO_VERSION=1.8.16
 - DJANGO_VERSION=1.9.11
 - DJANGO_VERSION=1.10.3

install:
 # Testing dependencies
 - pip install flake8 coverage python-coveralls moto
 # Required library dependencies
 - pip install boto six
 # Optional library dependencies
 - pip install celery django-celery django-kombu
 # The version of Django being tested against
 - pip install -q Django==$DJANGO_VERSION

script:
 - flake8 bakery
 - coverage run setup.py test

after_success:
 - coveralls
