language: python
sudo: false

python:
 - "2.7"
 - "3.4"
 - "3.5"

env:
 - DJANGO_VERSION=1.7.11
 - DJANGO_VERSION=1.8.7
 - DJANGO_VERSION=1.9

matrix:
  exclude:
    - python: "3.5"
      env: "DJANGO_VERSION=1.7.11"

install:
 - pip install pyflakes pep8 coverage python-coveralls moto
 - pip install django-celery
 - pip install -q Django==$DJANGO_VERSION

script:
 - pep8 bakery
 - pyflakes bakery
 - python setup.py install
 - coverage run setup.py test

after_success:
 - coveralls
